### ISSUE TITLE
getConnectorMetrics obp_api_request_id always null

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#623] opened 2017-07-03 09:55 UTC
Since last friday the field `obp_api_request_id` always seems null when calling `getConnectorMetrics`. https://github.com/OpenBankProject/OBP-API/commit/a224a4753ea226aa6652edd2852312da16e04007 talks about refactoring some names, maybe this broke it?

**Comment by simonredfern** [comment] 2017-07-03 12:53
Yes, the field obp_api_request_id has been renamed to correlation_id - but maybe not everywhere!

**Comment by constantine2nd** [comment] 2017-07-03 13:02
[List of all appearances of obp_api_request_id](https://github.com/search?p=1&q=org%3AOpenBankProject+obp_api_request_id&type=Code)

**Comment by simonredfern** [comment] 2017-07-12 07:55
@sebtesobe Can we close this now? (We should use correlation_id instead of obp_api_request_id)

**Comment by sebtesobe** [comment] 2017-07-12 08:25
No, it's still `obp_api_request_id`:

(`git_commit": "77cbc56cbcc8c14ee96eedcda0effa16b7275034"`)

```
GET /management/connector/metrics?start_date=2017-06-01

{
  "metrics":[{
    "connector_name":"LocalMappedConnector$",
    "function_name":"getBanks",
    "obp_api_request_id":null,
    "date":"2017-06-06T11:05:16Z",
    "duration":5
  },{
...
```

**Comment by constantine2nd** [comment] 2017-11-01 10:29
@sebtesobe Ready for testing.

**Comment by sebtesobe** [comment] 2017-11-06 11:11
Looks good to me: I can see them at e.g. https://apimanagersandbox.openbankproject.com/metrics/connector/?start_date=2017-11-05

**Comment by sebtesobe** [comment] 2017-11-06 11:13
The API is throwing a 500 when trying to filter, e.g. https://apimanagersandbox.openbankproject.com/metrics/connector/?start_date=2017-11-05&end_date=&limit=&offset=&connector_name=&function_name=&correlation_id=hiualbcmcuekufe7v7mho1qx

**Comment by constantine2nd** [comment] 2018-09-04 15:00
Due to continuous enhancements of the app this issue cannot be reproduced anymore.

**Closed by constantine2nd** 2018-09-04 15:00 UTC
Labels: bug
