### ISSUE TITLE
Build failed , Access denied 

### ISSUE THREAD

**Issue by prathyushmr** [OpenBankProject/OBP-API#79] opened 2016-07-05 08:40 UTC
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:41:59.799s
[INFO] Finished at: Tue Jul 05 13:43:50 IST 2016
[INFO] Final Memory: 21M/494M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project OBP-API: Could not resolve dependencies for project com.tesobe:OBP-API:war:1.0: Could not transfer artifact net.java.dev.jna:jna:jar:4.1.0 from/to scala-tools.releases (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by djKooks** [comment] 2016-07-24 03:23
@prathyushmr I am also facing with similar problem. Did you find the solution?

**Comment by sebtesobe** [comment] 2016-07-25 07:09
I can confirm these 'permission denied' errors. I could observe them for a couple of weeks now, but never had an issue with them, because it seems i have a local copy already:

```
[WARNING] Failure to transfer com.fasterxml.jackson.core:jackson-databind:2.8.2-SNAPSHOT/maven-metadata.xml from https://oss.sonatype.org/content/groups/scala-tools/ was cached in the local repository, resolution will not be reattempted until the update interval of scala-tools.releases has elapsed or updates are forced. Original error: Could not transfer metadata com.fasterxml.jackson.core:jackson-databind:2.8.2-SNAPSHOT/maven-metadata.xml from/to scala-tools.releases (https://oss.sonatype.org/content/groups/scala-tools/): Access denied to: https://oss.sonatype.org/content/groups/scala-tools/com/fasterxml/jackson/core/jackson-databind/2.8.2-SNAPSHOT/maven-metadata.xml , ReasonPhrase:Forbidden.
```


@pbozin do you have any idea what might cause this?

**Comment by prathyushmr** [comment] 2016-07-25 08:51
@djKooks No solution yet . I tried to browse the URL https://oss.sonatype.org/content/groups/scala-tools/
and it says 404 - Repository with ID="scala-tools" not found

**Comment by pbozin** [comment] 2016-07-25 08:58
Please pull latest version of OBP-API from github. The scala-tools directory was removed from sonatype, so pom.xml file was updated with correct link.

**Comment by sebtesobe** [comment] 2016-07-25 09:07
Choice, works for me now! @prathyushmr @djKooks is it ok for you?

**Comment by djKooks** [comment] 2016-07-30 05:02
@sebtesobe Issue on top has been cleared, but there are other problem.

```
ERROR - Failed to Boot! Your application may not run properly
java.lang.ExceptionInInitializerError
	at bootstrap.liftweb.Boot$$anonfun$boot$12.apply(Boot.scala:186)
	at bootstrap.liftweb.Boot$$anonfun$boot$12.apply(Boot.scala:186)
	at net.liftweb.common.Logger$class.info(Logging.scala:195)
	at net.liftweb.common.WrappedLogger.info(Logging.scala:246)
	at bootstrap.liftweb.Boot.boot(Boot.scala:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.liftweb.util.ClassHelpers$$anonfun$createInvoker$1.apply(ClassHelpers.scala:364)
	at net.liftweb.util.ClassHelpers$$anonfun$createInvoker$1.apply(ClassHelpers.scala:362)
	at net.liftweb.http.DefaultBootstrap$$anonfun$boot$1.apply(LiftRules.scala:2040)
	at net.liftweb.http.DefaultBootstrap$$anonfun$boot$1.apply(LiftRules.scala:2040)
	at net.liftweb.common.Full.map(Box.scala:610)
	at net.liftweb.http.DefaultBootstrap$.boot(LiftRules.scala:2040)
	at net.liftweb.http.provider.HTTPProvider$class.bootLift(HTTPProvider.scala:88)
	at net.liftweb.http.LiftFilter.bootLift(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.init(ServletFilterProvider.scala:40)
	at net.liftweb.http.LiftFilter.init(LiftServlet.scala:928)
	at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:97)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:713)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.jetty.plugin.Jetty6PluginWebAppContext.doStart(Jetty6PluginWebAppContext.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.plugin.Jetty6PluginServer.start(Jetty6PluginServer.java:132)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:454)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:396)
	at org.mortbay.jetty.plugin.AbstractJettyRunMojo.execute(AbstractJettyRunMojo.java:210)
	at org.mortbay.jetty.plugin.Jetty6RunMojo.execute(Jetty6RunMojo.java:184)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException: An Empty Box was opened.  The justification for allowing the openOrThrowException was OBP-00001: Hostname not specified. Could not get hostname from Props. Please edit your props file. Here are some example settings: hostname=http://127.0.0.1:8080 or hostname=https://www.example.com
	at net.liftweb.common.EmptyBox.openOrThrowException(Box.scala:697)
	at net.liftweb.common.EmptyBox.openOrThrowException(Box.scala:665)
	at code.api.Constant$.<init>(constant.scala:12)
	at code.api.Constant$.<clinit>(constant.scala)
	... 63 more
```
Do you know about this?

**Comment by simonredfern** [comment] 2016-07-30 09:25
please see the error towards the bottom of the stack trace:  

Caused by: java.lang.NullPointerException: An Empty Box was opened.  The justification for allowing the openOrThrowException was OBP-00001: Hostname not specified. Could not get hostname from Props. Please edit your props file. Here are some example settings: hostname=http://127.0.0.1:8080 or hostname=https://www.example.com

**Comment by simonredfern** [comment] 2016-07-30 09:27
@djKooks please see my note above.

**Comment by djKooks** [comment] 2016-07-30 23:47
@simonredfern Yes. I already fixed to 'hostname=http://127.0.0.1:8080' at .default.props and test.default.props file, but still shows this error. Is there other file do I have to change?

Thanks

**Comment by djKooks** [comment] 2016-08-06 07:30
@simonredfern I saw this line on README.md.

```
* In src/main/resources/props create a <yourloginname>.default.props for development. Set connector=mapped
```
What is <yourloginname>. Where can I define this?

**Comment by pbozin** [comment] 2016-08-09 15:48
@djKooks Either use username used to login into the OS, or just name the props file "default.props" (without the leading dot). 

Closing this issue since updating the scala-tools link fixed the initial problem.

**Closed by pbozin** 2016-08-09 15:48 UTC

**Comment by djKooks** [comment] 2016-08-12 00:49
@pbozin Thanks! Do you mean is it fine to set prop file as 'yourusername.props' or 'default.props'?
Could you share about 'scala-tool link fixed'?

**Comment by VGerris** [comment] 2024-12-23 22:57
If you can issues with Maven resolving http :
cat ~/.m2/settings.xml
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd">
     <mirrors>
          <mirror>
               <id>maven-default-http-blocker</id>
               <mirrorOf>dummy</mirrorOf>
               <name>Dummy mirror to override default blocking mirror that blocks http</name>
               <url>http://0.0.0.0/</url>
               <blocked>false</blocked>
         </mirror>
    </mirrors>
</settings>
```

Build the parent project to build the jar, then the api project can be built.
Thre are other problems in the pom.xml file but they should not prevent the app from starting.
