### ISSUE TITLE
future timeout problem

### ISSUE THREAD

**Issue by tawoe** [OpenBankProject/OBP-API#632] opened 2017-07-05 19:21 UTC
api becomes slow and finally unresponsive due to future timeouts.
some snippets: (full logs: [full logs](https://www.dropbox.com/sh/v6glgr52jn1xl6y/AABo5tyiEMQw6zU5JLunmcECa?dl=0)

2017-07-05 16:18:41 qtp815992954-604 Boot [ERROR] Exception being returned to browser when processing /obp/v3.0.0/my/accounts
java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)

2017-07-05 16:31:57 qtp815992954-606 KafkaMappedConnector_JVMcompatible [ERROR] getTransactions-ClassCastException
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to net.liftweb.json.JsonAST$JValue
	at code.bankconnectors.KafkaHelper$class.process(KafkaHelper.scala:37)

2017-07-05 16:48:24 qtp815992954-1174 KafkaMappedConnector_JVMcompatible [ERROR] getBankAccount-TimeoutException
java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)

2017-07-05 17:03:43 qtp815992954-1329 Boot [ERROR] Exception being returned to browser when processing /obp/v2.1.0/banks/00100/accounts/83b96bb4-ae2c-3e90-ad2c-8ce0b4b0023b/owner/transactions
java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)

**Comment by pbozin** [comment] 2017-07-05 20:23
Can you please post full log file? In order to debug the cause at least 10 seconds before each exception is needed. Maybe post gzipped log file, becaiuse it might be huge

**Comment by hongwei1** [comment] 2017-07-05 20:39
@pbozin Here all more logs 
https://drive.google.com/open?id=0BwW7-yM0BYFGdS1RbDREaWRyUEU

**Comment by simonredfern** [comment] 2017-07-05 21:08
That folder was empty - now being updated.

**Comment by tawoe** [comment] 2017-07-06 05:32
The dropbox link does not work?

**Comment by hongwei1** [comment] 2017-07-06 05:38
@tawoe It is working

**Comment by simonredfern** [comment] 2017-07-11 00:31
Closing this and will open as separate ticket (issue is with updateUserAccountViews which needs tuning.)

**Closed by simonredfern** 2017-07-11 00:31 UTC
